FROM node:20-bullseye as builder

WORKDIR /usr/app
COPY . .

ARG PUBLIC_STRIPE_KEY
ARG SECRET_STRIPE_KEY

ENV PUBLIC_STRIPE_KEY=$PUBLIC_STRIPE_KEY
ENV SECRET_STRIPE_KEY=$SECRET_STRIPE_KEY

EXPOSE 3000
CMD ["node", "build/index.js"]
